apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sinkreceiver-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: sinkreceiver-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - sinkreceiver
  commonName: sinkreceiver.{{ .Release.Namespace }}.svc.cluster.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - sinkreceiver.{{ .Release.Namespace }}.svc.cluster.local
    - sinkreceiver
    - sinkreceiver.{{ .Release.Namespace }}
    - sinkreceiver.{{ .Release.Namespace }}.svc
  issuerRef:
    name: sinkreceiver-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
